[package]
name = "rusty-wrenches"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "fix-nested-directories"
path = "src/bin/fix-nested-directories.rs"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"


[dev-dependencies]
rand = "0.8"
